name: Bug report
description: Report a bug with this package.
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        * Provide a general summary of the issue in the **title**.
        * Add **labels** to help the developers triage the issue.

  - type: checkboxes
    id: documentation
    attributes:
      label: Solution to issue cannot be found in the documentation.
      description: |
        I read [the Aurora documentation](https://docs.aurora.algorithmiq.fi/) and could not find the solution for my problem there.
      options:
        - label: I checked the documentation.
          required: true

  - type: textarea
    id: issue
    attributes:
      label: Describe the issue
      description: |
        Please describe the issue you are experiencing:
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: |
        Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant.
    validations:
      required: true
      
  - type: textarea
    id: possible-solution
    attributes:
      label: Possible solution(s)
      description: |
        Please describe any solution(s) you have considered.
    validations:
      required: false

  - type: textarea
    id: environment-info
    attributes:
      label: Environment info
      description: |
        Please share your virtual environment information by running `micromamba list` _and_ `pip list`. Enter the outputs below.
        _Note:_ This will be automatically formatted as code.
      value: | 
        <details>
        <summary>Micromamba</summary>
        ```shell
        Copy-paste the output of the micromamba list command here.
        ```
        </details>
        
        <details>
        <summary>Pip</summary>
        ```shell
        Copy-paste the output of the pip list command here.
        ```
        </details>
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: |
        Please provide any additional information on the issue that might help reproducing/troubleshooting/fixing it.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Algorithmiq/.github/blob/adeabc4dd697d82d1f1055abc8c1f908ddcd6f41/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
      
