name: General question
description: Ask a general question
labels: question
body:
  - type: checkboxes
    id: documentation
    attributes:
      label: Solution to issue cannot be found.
      options:
        - label: I checked the documentation.
          required: true
        - label: I looked for similar issues.
          required: true
        - label: I did a quick internet search.
          required: true

  - type: textarea
    id: comment
    attributes:
       label: "Comment:"

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Algorithmiq/.github/blob/adeabc4dd697d82d1f1055abc8c1f908ddcd6f41/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
