name: Update lockfiles

on:
  workflow_dispatch:
  schedule:
    - cron: 0 5 1 * *

jobs:
  pixi-update:
    permissions:
      contents: write
      pull-requests: write
    uses: Algorithmiq/.github/.github/workflows/update-pixi-lockfile.yml@v1.0.0
    secrets: inherit