name: Generate Python sdist

on:
  workflow_call:

jobs:
  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # such that setuptools_scm can do its job correctly

      - name: Build SDist
        run: |
          pipx install uv
          pipx run build --verbose --sdist --installer=uv

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
